CUDA_VISIBLE_DEVICES=3 python3 main.py \
--dataset moseldmp \
--num_epochs 40 \
# --dropout_a 0.2 \
# --dropout_v 0.5 \
# --dropout_prj 0.1 \
# --multiseed \
# --add_va \
# --n_layer 1 \
# --d_vh 32 \
# --d_ah 32 \
# --d_vout 32 \
# --d_aout 32 \
# --bidirectional \
# --d_prjh 128 \
# --pretrain_emb 512 \
# --hidden_size 768 \
# --gradient_accumulation_step 5 \
# --batch_size 32 \
# --clip 0.8 \
# --lr_main 0.0001 \
# --lr_T5 3e-4 \
# --lr_adapter 0.0001 \
# --lr_info 0.0001 \
# --weight_decay_main 1e-4 \
# --weight_decay_adapter 1e-4 \
# --weight_decay_T5 1e-4 \
# --weight_decay_info 1e-4 \
# --embed_dropout 1e-4 \
# --attn_dropout 1e-4 \
# --num_heads 2 \
# --relu_dropout 1e-4 \
# --res_dropout 1e-4 \
# --num_layers 2 \
# --optim Adam \
# --when 20 \
# --patience 10 \
# --update_batch 1 \
# --log_interval 100 \
# --seed 111 \
# --use_adapter True \
# --adapter_name ffn \
# --adapter_layer 3 \
# --fine_T5 True \
# --adam_epsilon 1e-8 \
# --save True \
# --info_nce False \
# --use_info_nce_num 3 \
# --use_cl False \
# --cl_name info_nce \
# --use_prefix_p False \
# --prompt_hidden_size 64 \
# --prefix_hidden_size 64 \
# --num_hidden_layers 1 \
# --prefix_projection False \
# --hidden_dropout_prob 0.3 \
# --s_dim 30 \
# --multi True \
# --fuse True \
# --pred_type classification \